# Generated by Django 6.0.4 on 2026-04-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_custom_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE public.tasks_historicaltask
                ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';
            """,
            reverse_sql="""
                ALTER TABLE public.tasks_historicaltask
                DROP COLUMN IF EXISTS description;
            """
        ),
    ]
